openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Restful API Design Account Demo'
  description: 'A demonstration on a Restful API contract.'

tags:
  - name: Payer API
    description: "API to manage payer."
  - name: Account API
    description: "API to manage accounts."

paths:
  /payers:
    get:
      tags:
        - Payer API
      summary: "Find payers."
      description: "Get list of payers."
      operationId: findPayers
      responses:
        '200':
          description: "OK"
          content:
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PayerResource'
        '401':
          description: "Unauthorized"
        '403':
          description: "Forbidden"
        default:
          description: "Unexpected error"
      deprecated: false

    post:
      tags:
        - Payer API
      summary: "Create new payer."
      description: "Create/Replace payer by id."
      operationId: createPayer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PayerResource'
      responses:
        '200':
          description: "OK"
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/PayerResource'
        '401':
          description: "Unauthorized"
        '403':
          description: "Forbidden"
        default:
          description: "Unexpected error"
      deprecated: false
  /payers/{payerId}:
    get:
      tags:
        - Payer API
      summary: "Find payer by id."
      description: "Find by id."
      operationId: findPayer
      parameters:
        - name: payerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "OK"
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/PayerResource'
        '401':
          description: "Unauthorized"
        '403':
          description: "Forbidden"
        default:
          description: "Unexpected error"
      deprecated: false

    put:
      tags:
        - Payer API
      summary: "Create/Replace payer."
      description: "Create/Replace payer by id."
      operationId: createReplacePayer
      parameters:
        - name: payerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "OK"
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/PayerResource'
        '401':
          description: "Unauthorized"
        '403':
          description: "Forbidden"
        default:
          description: "Unexpected error"
      deprecated: false

    patch:
      tags:
        - Payer API
      summary: "Update payer."
      description: "Update payer by id."
      operationId: updatePayer
      parameters:
        - name: payerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "OK"
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/PayerResource'
        '401':
          description: "Unauthorized"
        '403':
          description: "Forbidden"
        default:
          description: "Unexpected error"
      deprecated: false

    delete:
      tags:
        - Payer API
      summary: "Delete payer by id."
      description: "Delete by id."
      operationId: removePayer
      parameters:
        - name: payerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: "OK"
        '401':
          description: "Unauthorized"
        '403':
          description: "Forbidden"
        default:
          description: "Unexpected error"
      deprecated: false

  /payers/{payerId}/accounts:
    get:
      tags:
        - Account API
      summary: "Find accounts."
      description: "Find payer accounts."
      operationId: findPayerAccounts
      parameters:
        - name: payerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "OK"
          content:
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountResource'
        '401':
          description: "Unauthorized"
        '403':
          description: "Forbidden"
        default:
          description: "Unexpected error"
      deprecated: false

  /payers/{payerId}/accounts/{accountNumber}:
    get:
      tags:
        - Account API
      summary: "Find account."
      description: "Find payer account."
      operationId: findPayerAccount
      parameters:
        - name: payerId
          in: path
          required: true
          schema:
            type: string
        - name: accountNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "OK"
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/AccountResource'
        '401':
          description: "Unauthorized"
        '403':
          description: "Forbidden"
        default:
          description: "Unexpected error"
      deprecated: false

  /accounts/{accountNumber}:
    get:
      tags:
        - Account API
      summary: "Find account."
      description: "Find account."
      operationId: findAccount
      parameters:
        - name: accountNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "OK"
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/AccountResource'
        '401':
          description: "Unauthorized"
        '403':
          description: "Forbidden"
        default:
          description: "Unexpected error"
      deprecated: false

    delete:
      tags:
        - Account API
      summary: "Find account."
      description: "Find account."
      operationId: closeAccount
      parameters:
        - name: accountNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: "ACCEPTED"
        '401':
          description: "Unauthorized"
        '403':
          description: "Forbidden"
        default:
          description: "Unexpected error"
      deprecated: false

components:
  schemas:
    PayerResource:
      type: object
      properties:
        payerId:
          type: string
        payerName:
          type: string
      required:
        - payerId
        - payerName

    AccountResource:
      type: object
      properties:
        accountNumber:
          type: string
        accountName:
          type: string
        accountType:
          type: string
          example: Current account, Savings account, Transmission account
      required:
        - accountNumber
        - accountName
        - accountType

# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Richard.Hudson/Restful-API-Design-Demo/1.0.0